[package]
name = "glommio-bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glommio = "0.7.0"
common-bench = { path = "../common-bench" }
futures-lite = "1.12.0"